name: Publish Snapshot
on: workflow_dispatch

jobs:
  publish:
    uses: thomasm-ttd/SharedWorkflows/.github/workflows/publish-snapshot.yaml@main

    #runs-on: ubuntu-latest
    #steps:
      #- uses: actions/checkout@v2
      #- uses: ./.github/workflows/download_gpg_key
      #  with:
      #    key: ${{ secrets.GPG_KEY }}
      #- name: Check Version is snapshot
      #  id: check_version
      #  uses: ./.github/workflows/check_version
      #  with:
      #    needs_snapshot: 'true'
      #- name: Deploy Snapshot
      #  run: mvn -B clean compile test
